### ISSUE TITLE
Add support for eager-loading

### ISSUE THREAD

**Issue by rungta** [ethercreative/simplemap#105]
### Description

It would be great if we could eager-load SimpleMap fields [using the `with` parameter on element queries](https://docs.craftcms.com/v3/dev/eager-loading-elements.html).

### Steps to reproduce

1. Create a SimpleMap field called `myMapField`
2. `{{ dump(craft.entries.with(['myMapField']).one()) }}`

**Comment by Tam** [comment]
SimpleMap can't be eager-loaded because it doesn't use an element type to store its data.

**Comment by Tam** [comment]
To expand on this a bit, SimpleMap doesn't need eager loading since its data is loaded as part of the initial element query (similar to the data being loaded from the content table). Changing this to an element based method (à la matrix blocks) would add more complexity and overhead (more SQL queries), likely increasing the execution time.

**Comment by rungta** [comment]
Ah okay, makes sense. Thanks for explaining. :)
