### ISSUE TITLE
Compatibility with Feedme

### ISSUE THREAD

**Issue by shornuk** [ethercreative/simplemap#112]
Hi,

Verbb has updated Feedme in the latest beta to include support for importing into Simplemap fields. (Something we've got a requirement for with a few sites.)

They mention that there is an issue, see here...
https://github.com/verbb/feed-me-helpers/issues/5#issuecomment-432108347

Any chance this can be addressed to make importing into Simplemap work? Thanks! 👍

**Comment by engram-design** [comment]
More than happy to be part of the conversation to explain the issue. I've tried my best to explain:

Essentially, its these lines:
https://github.com/ethercreative/simplemap/blob/v3/src/services/MapService.php#L159-L162
That overwrite the element (the owner entry's) content unless its a direct post request, which in this case, its not. Therefore, that code will create a blank, empty model rather than the populated one setup by Feed Me.

Feel free to get in touch via Slack (crawf)

**Comment by bryantAXS** [comment]
Any idea when this one is going to roll out? Looks like it has been implemented?

**Comment by justjoolz** [comment]
I tried the dev version it and it doesn't seem to work :( 

Anyone had any success importing data into a SimpleMap field?
