### ISSUE TITLE
Map not rendered/displayed after initial request

### ISSUE THREAD

**Issue by superflausch** [ethercreative/simplemap#255]
### Description

We noticed that on one of our projects the map doesn’t get rendered at all (no output). Not sure since when this behaviour started. We now run CraftCMS (3.4.16) and Maps (3.8.3) versions and still see this issue.

It looks like it is related to Craft’s own template caching. As the initial request/render shows the map, also when I disable caching at all the map gets rendered.

It’s a simple map field, with an address and the following TWIG code:

```
    {{ block.map.embed({
      id: 'map',
      markers: [{}],
        width: '100%',
        height: 400,
    })|attr({
      class: 'c_map'
  }) }}
```

We are using the PRO Version.

### Steps to reproduce

1. Setup
2. Add maps field
3. Input/Select Adress/Point
4. Render map on frontend (see above)

### Additional info

- Craft version: 3.4.16
- Maps version: 3.8.3
- PHP version: 7.3.17
- Database driver & version: MySQL 5.5.5

**Comment by Tam** [comment]
The issue is that Maps can't inject the JavaScript if the embed has been cached (if you're only caching the markup for the embed and not the entire page). The JavaScript is injected using Crafts built-in methods, which sticks the code at the end of the page. When you reload the page Craft outputs the cached markup, but never injects the JS.
The only workaround is to cache the entire page, including the injected JS, or not caching the map embed. You might also be able to get away with just caching your `{{  endBody() }}`, but that might not be a great idea.
