### ISSUE TITLE
"parts" functionality doesn't return anything

### ISSUE THREAD

**Issue by sam327** [ethercreative/simplemap#49]
It looks like in a recent update, the "parts" functionality quit working for me. I'm trying to return a list of cities, like so: 

- Boston, MA
- New York, NY
- Washington, DC

And my code looked like so.
````<li>{{ entry.map.parts.locality }}, {{ entry.map.parts.administrative_area_level_1_short }}</li>````
And it was working. But now it renders ````<li>, </li>````

However if I use the full address ````<li>{{ entry.map.address }}</li>````
then I get actual data back:
 ````<li>1600 Pennsylvania Ave NW, Washington, DC 20500</li>````

**Comment by sam327** [comment]
Scratch that, it looks like it didn't like one particular address, and thus killed _everything_. 

Opening and resaving was the fixer. There's a couple items in my list that aren't showing the lat/long, and those are the offenders. Clicked in the field, re-selected the location address, and saved the entry. And all is good.

All it took was filing a ticket before I noticed what was actually wrong.

**Comment by jonsuther** [comment]
I am also having this issue, but maybe I just don't know what I'm doing because I am a noob.

This is what I'm using:

{{ entry.locationAddress.parts.street_address }}

and this is what I'm putting in the field: 2831 15th St NW, Washington D.C., DC 20009, USA

What I want to display is:

2831 15th St NW, Washington D.C., DC

Basically just want street, city, state
