### ISSUE TITLE
Some seaches not returning results

### ISSUE THREAD

**Issue by shornuk** [ethercreative/simplemap#53]
Hi, 
Not sure if this is plugin or Google related. 
I have location field set up. I have a search field on my front end that queries this location field. It's mainly fine, but I have noticed that it will only return results if the search string matches what the Google address autocomplete would be. 
For example, when I search for "Winchester" I get no results, but if I search for "Winchester, United Kingdom" I get the relevant results. 

Any ideas?

**Comment by Tam** [comment]
It's hard to tell with out some examples of your code, but at a guess I'd say that

**Comment by Tam** [comment]
It's hard to say without examples of your code, but at a guess I'd say it's because the Winchester that is being searched for is a different one than the Winchester in the UK. 

The location search converts the address to a LatLng (via Google's Geocoding), then searches by that rather than the physical address. This ties in to #52 and the ability to search by parts of the address (in this case `city: "Winchester"`), which is something we'll be adding in the future.

**Comment by shornuk** [comment]
Ah ok, that makes sense. We're going to append "UK" to the search query as that seems to cover it.
