### ISSUE TITLE
Performance Issue (Waiting for table metadata lock)

### ISSUE THREAD

**Issue by samhibberd** [ethercreative/simplemap#55]
Hi There,

We have been running into some performance issues on a high traffic site and have caught some queries in MySQL causing Apache processes to backup and subsequently crash.

Our hosts (Arcustech) worked with Brad (Craft) to try and work out the cause and suspect it might be coming from one of the queries generated by simple maps. 

I thought it would be good to share our findings and ask if you have run into anything similar or have any ideas of how to debug / fix the issue.

> I worked for about 30 minutes today with Brad Bell here in the Craft CMS offices in Bend, OR. and we found a few things.
> 
> First the query I caught in full this morning that was running multiple times at once on the MySQL server this morning when we restarted mysql to clear them out, is in the text file I have attached.
> 
> Brad took a copy of your production database and installed it on his local test system here in the Craft office, and in Navicat ran the above query directly against your database copy. It took his system here over 4 minutes to run the above query, and looking at an analysis of what the query had to do there were well over 200 million requests to mysql to read the next row in tables. This obviously is both slow and resource intensive, and is clearly triggered by the simplemap plugin.
> 
> Unfortunately looking through both your craft templates and the simplemap code Brad could not pinpoint exactly what maybe creating the 8 LEFT JOINs to the craft_relations table which itself has 277k+ entries.
> 
> The conclusion is the site slowdowns are not directly related to anything Craft CMS core code wise or the server configuration. With that said, if the SimpleMap plugin developer can maybe supply some feedback on the plugin usage, the amount of data you are running the above query against, and possibly some alternatives to making it more optimal.
> 
> I know this does not solve the issue, as we are still unsure exactly what feature or search on your site will generate the above query, but at least we hope it leads you and/or your developer towards a path of finding out.
> 
> Please let us know if you have further questions, and at least from a coding standpoint you can reach out to Craft support too as they have background at looking at this now too.

[sql-query.txt](https://github.com/ethercreative/simplemap/files/1411780/sql-query.txt)

Many thanks,

Sam

**Comment by Tam** [comment]
Hi Sam,

I don't think I've had anything try to run 200 million+ requests before, that's impressive!

This isn't something we've come across before so it would be really useful to have access to a copy of your database, your templates, and any plugins (custom or otherwise) that you are using so we can better debug the issue. There's nothing in the SimpleMap code that would be causing those joins, but there could be something affecting it.

It sounds like you have a *lot* of SimpleMap entries and I agree with Brad & Arcustech that our current method of location searching is a bit slow & resource intensive, especially when you have such a large number of entries. We're looking into improving this and should be releasing an update, if not today then early next week at the latest, that should drastically reduce the number of next row requests.

You can email me directly (tam@ethercreative.co.uk) if you've got anything you don't want to share publicly here!

Thanks,
Tam

**Comment by Tam** [comment]
Closing this following the v1.7.0 release
