### ISSUE TITLE
No API key warning

### ISSUE THREAD

**Issue by paul-frost** [ethercreative/simplemap#7]
I'm getting a:
 "Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"
in the console (whilst on the entry editing in the CP) even though I have added a key in the SimpleMap settings.

**Comment by Tam** [comment]
The API key setting is for the server-side Google Maps Geocoding API (this allows the searching and sorting entries by location functionality). That warning is because we're not using an API key on the front-end Google Maps API which is *technically* allowed and means one less API key to worry about. If it becomes an issue in the future we'll a setting.

**Comment by patashe** [comment]
I'm getting "Google Maps API error: MissingKeyMapError" and "Google Maps API warning: NoApiKeys" when I have the following credentials set up in google and the Key saved in the plugin settings:

- Google Maps Geocoding API
- Google Maps JavaScript API

Is there something I'm missing?

**Comment by Tam** [comment]
@patashe Fixed in v1.2.2

**Comment by patashe** [comment]
thanks @Tam, that fixed the issue.
