### ISSUE TITLE
Error upon saving in Craft 2.6.3009

### ISSUE THREAD

**Issue by tigerchick** [ethercreative/simplemap#92]
### Description
When saving an entry with a Simplemap field (in Matrix - untested outside of a Matrix), the following error is given:
Internal Server Error
array_key_exists() expects parameter 2 to be array, null given

### Steps to reproduce

1. Update to latest Simplemap version 1.8.2
2. Update to latest Craft 2 version -  2.6.3009
3. Save entry with simplemap field

### Additional info

- Craft version: 2.6.3009
- SimpleMap version: 1.8.2
- PHP version: 7.0.27

**Comment by taylordaughtry** [comment]
I'm seeing this as well on Craft 2.6.2988 with SimpleMap version 1.8.2, with the SimpleMap field outside any Matrix field; simply the usual field on an entry.

Digging in, it looks like the `$data` value being provided from the `SimpleMap_MapFieldType` content is `null` when it's being saved, which is why it's throwing an error. I haven't looked into it enough to know exactly _why_ that is. The field has content.

*EDIT:* Found the issue. The `ContentModel` fetches the column data for the entry—but Simple Map doesn't use that column; it has a separate table. So when that content is checked, it's `null`, which is throwing the error. PR is submitted [here](https://github.com/ethercreative/simplemap/pull/94).

**Comment by tigerchick** [comment]
That's brilliant Taylor - thank you for looking into this. Hopefully your solution will be merged quickly.

**Comment by AdamVig** [comment]
@Tam I am experiencing this same problem on SimpleMap version `3.3.3` with Craft `3.0.1`. Can you merge the fix into the `v3` branch as well?

**Comment by jannisborgers** [comment]
I’m still receiving the same error with SimpleMap 3.3.3 and Craft 3.0.2.

**Comment by Tam** [comment]
@AdamVig @jannisborgers I've just tested saving a map in a matrix and was unable to re-create this error. If this is still an issue, could you open a new issue and include the error message you are seeing?

**Comment by AdamVig** [comment]
@Tam Thanks for your reply. The plugin is now working for me.

It looks like a recent Craft update fixed it, because that is the only thing that has changed since I originally commented.
